---
title: "cor_plots"
author: "Christian Nilsen and Sarah Welsh"
date: "4/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PerformanceAnalytics)
library(readr)
library(tidyverse)
library("Hmisc")
library(GGally)
library(corrplot)
```


```{r loads data, echo=FALSE}
setwd("~/kingcountysw")
kc_reduced <- read_csv("Data/SubbasinAttributes_corplot1.csv", 
    col_types = cols(MedianSpawnerMortality = col_double()))
```


```{r create df, echo=FALSE}
cor_df <- kc_reduced %>%
  select_if(is.numeric) %>%
  scale(center=TRUE,scale=TRUE) %>% as.data.frame()

plot_cols1 <- c("Cat1_Count",
                    "Cat2_Count",
                    "Cat4A_Count",
                    "Cat4B_Count",
                    "Cat4C_Count",
                    "Cat5_Count",
                    "305b_Listings_Cat4+5",
                    "ApprovedTMDLCount",
                    "DevelopingTMDLCount",
                    "FishPassageCount",
                    "CriticalHabitatLength_ft",
                    "ShellfishCount",
                    "SwimmingBeachPercentage",
                    "SwimmingTributaryPercentage"
                    )

plot_cols2 <- c("CohoPresence",
                    "UrbanGrowthBoundaryPercentage",
                    "ICIAreaPercentage",
                    "RoadwayLength_ft",
                    "SidewalkLength_ft",
                    "CrashesCount",
                    "CrashDensity",
                    "SidewalkDensity",
                    "PercentBuiltBefore1990",
                    "PercentImpervious",
                    "MeanFlowDurationIndex",
                    "HeatIndex",
                    "MedianOpportunityIndex",
                    "MeanAnnualAvgDailyTrips",
                    "Median2018EquityScore",
                    "MedianPavementCondition",
                    "MedianSpawnerMortality",
                    "UrbanHeat"
                    )
                    
plot_cols3 <- c("WQBETotalCopper",
                    "WQBETotalZinc",
                    "WQBETotalNitrogen",
                    "WQBETotalPhosphorus",
                    "WQBETotalSuspendedSolids",
                    "WQBETotalPCB",
                    "WQBETotalPBDE",   
                    "WQBETotalPAH",
                    "WQBE_BEHP",
                    "WQBEFecalColiformBacteria",
                    "WQBEAnnualRunoff",
                    "MeanAnnualTSSLoad",
                    "MeanAnnualCopperLoad",
                    "MeanAnnualPhosphorusLoad",
                    "MeanAnnualZincLoad",
                    "MeanAnnualTKNLoad",
                    "Average_BIBI",
                    "FacilitiesCount",
                    "BRE_FaciltiesCount",
                    "DrainagetoPSensitiveLake"
                    )
```

```{r plot, echo=FALSE}
cor_plot_img <- PerformanceAnalytics::chart.Correlation(cor_df %>%
                                                          dplyr::select(
                                                          all_of(plot_cols1))
                                                          , na.action=stats::na.pass
)
cor_plot_img


cor_plot_img2 <- PerformanceAnalytics::chart.Correlation(cor_df %>%
                                                           dplyr::select(
                                                             all_of(plot_cols2))
                                                             , na.action=stats::na.pass
                                                          )
cor_plot_img2

cor_plot_img3 <- PerformanceAnalytics::chart.Correlation(cor_df %>%
                                                           dplyr::select(
                                                             all_of(plot_cols3))
                                                             , na.action=stats::na.pass
                                                          )
cor_plot_img3
```

```{r plot 2, echo=FALSE}

COL2(diverging = c("RdBu", "BrBG", "PiYG", "PRGn", "PuOr", "RdYlBu"), n = 200)

#rcorr plots
cor_5_1 <- rcorr(as.matrix(cor_df %>%
                 dplyr::select(
                   all_of(plot_cols1)))
                 )
M_1 <- cor_5_1$r
p_mat_1 <- cor_5_1$P
p_mat_1[is.na(p_mat_1)] <- 1

cor_5_2 <- rcorr(as.matrix(cor_df %>%
                 dplyr::select(
                   all_of(plot_cols2)))
                 )
M_2 <- cor_5_2$r
p_mat_2 <- cor_5_2$P
p_mat_2[is.na(p_mat_2)] <- 1

cor_5_3 <- rcorr(as.matrix(cor_df %>%
                 dplyr::select(
                   all_of(plot_cols3)))
                 )
M_3 <- cor_5_3$r
p_mat_3 <- cor_5_3$P
p_mat_3[is.na(p_mat_3)] <- 1

ibm.palette <- colorRampPalette(c(
  "#648FFF",
  "#785EF0",
  "#DC267F",
  #"#785EF0",
  #"#648FFF",
  "#FE6100",
  "#FFB000"
),
space = "Lab")

ccpal <- colorRampPalette(c(
  "#2887a1",
  "#6cc2da",
  #"#778868",
  #"#b5b991",
  "#bdbdbd", "#bdbdbd", "#bdbdbd", "#bdbdbd", "#bdbdbd", "#bdbdbd","#bdbdbd", "#bdbdbd","#bdbdbd",
  #"#edbb8a",
  #"#de8a5a",
  "#F3693F",
  "#bf360c"

))


corrplot(M_1, type = "lower", order = "hclust",method = "number" ,tl.col = "black",
         addCoefasPercent = FALSE, col =ccpal(20),
         p.mat_1 = p_mat_1, sig.level = 0.01, tl.cex=1)

corrplot(M_2, type = "lower", order = "hclust",method = "number" ,tl.col = "black",
         addCoefasPercent = FALSE, col =ccpal(20),
         p.mat_2 = p_mat_2, sig.level = 0.01, tl.cex=1)
         
corrplot(M_3, type = "lower", order = "hclust",method = "number" ,tl.col = "black",
         addCoefasPercent = FALSE, col =ccpal(20),
         p.mat_3 = p_mat_3, sig.level = 0.01, tl.cex=1)

cbPalette <- colorRampPalette(c(
  '#a6611a',
  '#dfc27d','#dfc27d',
  '#f5f5f5','#f5f5f5','#f5f5f5','#f5f5f5','#f5f5f5',  '#f5f5f5','#f5f5f5','#f5f5f5','#f5f5f5','#f5f5f5',
  '#80cdc1','#80cdc1',
  '#018571'



                               ))

ggpairs(cor_df %>%
                 dplyr::select(
                   all_of(plot_cols1))
        , title="correlogram with ggpairs()",
        upper = list(continuous = wrap("cor", size = 2)))

ggpairs(cor_df %>%
                 dplyr::select(
                   all_of(plot_cols2))
        , title="correlogram with ggpairs()",
        upper = list(continuous = wrap("cor", size = 2)))
        
ggpairs(cor_df %>%
                 dplyr::select(
                   all_of(plot_cols3))
        , title="correlogram with ggpairs()",
        upper = list(continuous = wrap("cor", size = 2)))
```
