---
title: "cor_plots"
author: "Christian Nilsen and Sarah Welsh"
date: "4/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PerformanceAnalytics)
library(readr)
library(tidyverse)
library("Hmisc")
library(GGally)
library(corrplot)
library(car)
library(DataExplorer)
```


```{r loads data, echo=FALSE}
#setwd("~/kingcountysw")
kc_reduced <- read_csv("../data/cor_updated.csv", 
    col_types = cols(MedianSpawnerMortality = col_double())) %>% as.data.frame()

 # precip_and_cocs.sf <- read_csv("../data/precip_and_cocs.csv", 
 #     col_types = cols(`system:index` = col_skip())) %>% 
 #         #.geo = col_skip())) 
 #          as.data.frame() %>% sf::st_read()
 # 
  precip_and_cocs <- read_csv("../data/precip_and_cocs.csv", 
     col_types = cols(`system:index` = col_skip(),
         .geo = col_skip())) %>% 
          as.data.frame() %>% 
    rename( DecPrecipChange=pr_mean)

#colnames(kc_reduced) <- make.names(kc_reduced %>% colnames())
#colnames(precip_and_cocs) <- make.names(precip_and_cocs %>% colnames())

precip_and_cocs <- precip_and_cocs %>% dplyr::select(-c(
"log_copper_concentration_ug_per_L",
"log_p_concentration_ug_per_L", 
"log_tkn_concentration_ug_per_L", 
"log_tss_concentration_mg_per_L", 
"log_zinc_concentration_ug_per_L"
))

```

Calculate concentrations 
```{r}
#1 kg/year = 35315 mg/L 
# = 3.531e7 ug/L 
wqbe_loads = kc_reduced %>% select(starts_with('WQBE')) %>%  mutate(
    across(c(1:10),
           .fns = ~.*3.531e7/`WQBE Annual Runoff (ft^3/yr)`))

colnames(wqbe_loads) <- c(
"WQBE Total Copper concentration"                    ,
 "WQBE Total Zinc concentration"                      ,
 "WQBE Total Nitrogen concentration"                  ,
 "WQBE Total Phosphorus concentration"                ,
 "WQBE Total Suspended Solids concentration"          ,
 "WQBE Total PCB concentration"                       ,
 "WQBE Total PBDE concentration"                      ,
 "WQBE Total PAH concentration"                       ,
 "WQBE BEHP concentration"                            ,
 "WQBE Fecal Coliform Bacteria concentration",
 "WQBE Annual Runoff (ft^3/yr)" )


#replace with wqbe_loads 
kc_reduced <- kc_reduced %>% select(-c(starts_with('WQBE'))) %>% add_column(wqbe_loads)

```


```{r}
#remove columns from kc_reduced


remCols <- kc_reduced #%>% select(starts_with(c("Mean Annual")))#,"WQBE Total","WQBE BEHP","WQBE Fecal"))) %>% colnames()

#remCols
df2 <- kc_reduced# %>% dplyr::select(-all_of(remCols))#%>% na.omit()

df2 %>% colnames() %>% clipr::write_clip()
```

```{r}
#join data files 

joined <- df2 %>% merge.data.frame(precip_and_cocs, by.x = 'SWSID',by.y = 'Ph2_SWSID')

```


```{r create df, echo=FALSE}

#arrange columns 

metrics_config <- read_csv("../data/metrics_config.csv") %>% 
  filter(Goal != 0) %>% 
  arrange(Goal)

 


cor_df <- joined %>%
  select(metrics_config$metric)
  
colnames(cor_df) <- metrics_config$Alias  
  
cor_df <- cor_df %>%   
  select_if(is.numeric) %>%
  scale(center=TRUE,scale=TRUE) %>% as.data.frame()



```

```{r look at data}

DataExplorer::introduce(cor_df)
#86 complete rows 
DataExplorer::plot_missing(cor_df)

```

```{r}
#function to return vif for a dataframe 
calc_vif <- function(df){
  df <- df %>% mutate(rand = stats::runif(n = NROW(df)))
  M <- lm(rand~.,data=df)
  
  
  vif <- vif(M) %>% as.data.frame() %>% 
    rownames_to_column(('metric'))
  
  
  vif['metric'] <- lapply(vif['metric'], function(x) (gsub("`", "", x)))
  

  
  colnames(vif) <- c("metric","VIF")
  vif %>% clipr::write_clip()
  
  return(vif)
}
```

```{r}

calc_cor <- function(df,use="everything"){
  return(cor(df,use=use) %>% as.data.frame() %>% rownames_to_column('metric') )
}

```

```{r}

goal1 <- metrics_config %>% filter(Goal == 1)# %>% select(metric) %>% as.character()

goal1 <- metrics_config %>% 
  filter(Goal == 1) %>% 
  arrange(Subgoal) %>% 
  pull(Alias) %>% 
  sort()

goal2 <-metrics_config %>% 
  filter(Goal == 2) %>% 
    arrange(Subgoal) %>% 
  pull(Alias) %>% 
  sort() 

goal3 <-metrics_config %>% 
  filter(Goal == 3) %>% 
    arrange(Subgoal) %>% 

  pull(Alias) %>% 
  sort() 

goal4 <-metrics_config %>% 
  filter(Goal == 4) %>% 
    arrange(Subgoal) %>% 

  pull(Alias) %>% 
  sort() 


```

```{r}

## make table of aliases sorted by goal and subgoal


cor_df.2 <- cor_df %>% select(-c(`Sidewalk density`, `Crash density`, 
                                 `Pavement condition index`, BIBI))
# %>% select(c(all_of(c(goal3,goal2,goal3,goal4))))

# ,`WQBE Total Zinc (kg/yr)`,`WQBE BEHP (kg/yr)`,`WQBE Total Phosphorus (kg/yr)`,`WQBE Total PCB (kg/yr)`,`WQBE Total Copper (kg/yr)`,`WQBE Fecal Coliform Bacteria (10^12 CFU/year)`,`WQBE Total PAH (kg/yr)`,`WQBE Total Suspended Solids (kg/yr)`,`WQBE Total Nitrogen (kg/yr)`
# 
# 
# ))# %>% na.omit()

calc_vif_cor = function(df,use="everything"){
  vifs <- calc_vif(df)
  cors <- calc_cor(df,use)
  joined.df <- vifs %>% left_join(cors)# %>% left_join(vifs)
  
}
vif_table.complete.obs <- calc_vif_cor(cor_df.2,use="everythin") 
  

# iteratively remove metrics by vif 

calc_vif(cor_df.2 %>% select(-c(
  'WQBE Total Zinc concentration', 
  'WQBE BEHP concentration',
   'WQBE Total Phosphorus concentration',
   'WQBE Total Copper concentration',
  'WQBE Fecal Coliform Bacteria concentration',
  # 'WQBE Total Suspended Solids concentration', 
   'TNC TKN concentration',
   'TNC TSS concentration', 
     'TNC P concentration', 
  # 'WQBE Total PBDE concentration',
   'TNC Zinc concentration',
   'WQBE Total PCB concentration',
  # 'WQBE Total Nitrogen concentration',
   'Equity Score',
  # 'BRE Critical Facilities'
  # ,##
  # 'Percent within UGA',
   'BRE facilities', 
  # 'Flow duration index', 
  # 'Urban Heat Island'
  )
  )) %>% arrange(desc(VIF))
#vif_table.everything <- calc_vif_cor(cor_df.2,use="everything") 



```

```{r}
#make corplot with corrplot(M, order = 'hclust', addrect = 2)
library(corrplot)

vif_table.selected <- calc_vif_cor(cor_df.2,use='complete.obs')
vif_table.selected %>% clipr::write_clip()
vif_table.complete.obs %>% clipr::write_clip()
#vif_table.everything  %>% clipr::write_clip()

```
```{r}
library(dendextend)
spellman.dist <- as.dist(1 - cor(cor_df.2,use='complete.obs'))
spellman.tree <- hclust(spellman.dist, method="complete")


spellman.dend <- as.dendrogram(spellman.tree) # create dendrogram object

spellman.dend  %>%
 # dendextend::set("labels_cex", 0.2)  %>%
   hang.dendrogram %>% 
  plot_horiz.dendrogram(side=TRUE)  # plot horizontally




```

